class AssetsPics{
//TODO===========> Assets
  static const videocalledperson = "assets/videocalledperson.svg";

//TODO===========> bg
  static const appBarbg = "assets/bg/appBar_bg.png";
  static const background = "assets/bg/Background.png";
  static const bannerpng = "assets/bg/bannerbg.png";
  // static const banner = "assets/bg/bannerbg.svg";//
  static const bannerheart = "assets/bg/bannerheart.svg";
  static const bigheart = "assets/bg/bigheart.svg";
  static const bluebg="assets/bg/blue_bg.png";
  static const bookingCanceled = "assets/bg/bookingCanceled.png";
  // static const delteChat="assets/bg/delteChat.png";
  static const editBanner="assets/bg/editBanner.png";
  static const editBannerSvg="assets/bg/editBanner.svg";
  static const eventbg = "assets/bg/eventbg.svg";
  static const firstBg='assets/bg/first.png';
  // static const firstBgSvg='assets/bg/first.svg'; //
  static const heartblankbg2 = "assets/bg/heartblankbg2.svg";
  static const hearts = "assets/bg/hearts.svg";
  static const blackbackground = "assets/bg/introBlack.svg";
  static const introblackupperbg = "assets/bg/introblackupperbg.svg";
  // static const introblackupperbg = "assets/bg/introblackupperbg1.svg";
  // static const introwhiteShade = "assets/bg/introwhiteShade.png";//
  static const redbanner = "assets/bg/redError.svg";//
  static const removed = "assets/bg/removed.svg";
  static const reportbanner="assets/bg/reportbanner.png";
  static const reportbannerSvg="assets/bg/reportbanner.svg";
  static const secondBg='assets/bg/second.png';
  // static const secondBgSvg='assets/bg/second.svg';//
  static const sliderthird=  "assets/bg/sliderthird.png";
  // static String splashpng = "assets/bg/splash.png";
  // static String splash = "assets/bg/Splash.svg";
  static String splash = "assets/bg/splashh.png";
  static const thirdBg='assets/bg/third.png';
  // static const thirdBgSvg='assets/bg/third.svg';//
  static const unMatchedbg = "assets/bg/unMatchedbg.png";
  static const unMatchedbgsvg = "assets/bg/unMatchedbg.svg";
  static const verifyinprocess="assets/bg/verifyinprocess.png";
  // static const verifyinprocesssvg="assets/bg/verifyinprocess.svg";
  static const Videocallthumb="assets/bg/Videocallthumb.png";
  static const videodemo='assets/bg/videodemo.png';
  static const viewProfile = "assets/bg/viewProfile.svg";
  static const viewProfileplain = "assets/bg/viewProfile2.svg";


//TODO===========> icons
        // => bottomnavigationIcon
           static const evnetIcon = "assets/icons/bottomnavigationIcon/event1.svg";
           static const heartIcon = "assets/icons/bottomnavigationIcon/heart1.svg";
           // static const message = "assets/icons/bottomnavigationIcon/message.svg";
           static const msgIcon = "assets/icons/bottomnavigationIcon/message1.svg";
           static const profileIcon = "assets/icons/bottomnavigationIcon/profile1.svg";
           static const reelIcon = "assets/icons/bottomnavigationIcon/reel1.svg";
           static const selectedevnetIcon = "assets/icons/bottomnavigationIcon/selctedevent1.svg";
           static const selectedheartIcon = "assets/icons/bottomnavigationIcon/selctedheart.svg";
           static const selectedmsgIcon = "assets/icons/bottomnavigationIcon/selctedmessage.svg";
           static const selctedredmessage = "assets/icons/bottomnavigationIcon/selctedredmessage.svg";
           static const selectedprofileIcon = "assets/icons/bottomnavigationIcon/selctedprofile.svg";
           static const selectedredheartIcon = "assets/icons/bottomnavigationIcon/selctedredheart.svg";
           // static const selectedheartIcon = "assets/icons/bottomnavigationIcon/selectedheart.svg";
           static const selectedreelIcon = "assets/icons/bottomnavigationIcon/selectedreel.svg";
      // => circleavatar
            static const all = "assets/icons/circleavatar/all.svg";
            static const business = "assets/icons/circleavatar/business.svg";
            // static const circlebusiness = "assets/icons/circleavatar/circlebusiness.svg";
            // static const circlefood = "assets/icons/circleavatar/circlefood.svg";
            // static const circlemusic = "assets/icons/circleavatar/circlemusic.svg";
            // static const circlesport = "assets/icons/circleavatar/circlesport.svg";
            static const sample = "assets/icons/circleavatar/eventsec.png";
            static const food = "assets/icons/circleavatar/food.svg";
            static const music = "assets/icons/circleavatar/Music.svg";
            static const sample2 = "assets/icons/circleavatar/sampleContiner.png";
            static const selectbusiness = "assets/icons/circleavatar/scirclebusiness.svg";
            static const selectfood = "assets/icons/circleavatar/scirclefood.svg";
            static const selectsport = "assets/icons/circleavatar/scirclesport.svg";
            static const selectmusic = "assets/icons/circleavatar/selectcirclemusic.svg";
            static const selectall = "assets/icons/circleavatar/selectall.svg";
            static const sport = "assets/icons/circleavatar/sports.svg";
  static const about = "assets/icons/about.svg";
  static const acSetting = "assets/icons/accountsetting.svg";
  static const active = "assets/icons/active.svg";
  static const addImage = "assets/icons/addImage.svg";
  static const apple = "assets/icons/apple.png";
  static const arrow = "assets/icons/arrow.svg";
  static const arrowLeft = "assets/icons/arrow_left.svg";
  static const arroeRight = "assets/icons/arrow_right.svg";
  static const blacksaved1 = "assets/icons/blacksaved1.svg";
  static const blankCheckbox = "assets/icons/blankcheckbox.svg";
  // static const bluecampng = "assets/icons/bluecam.png";//
  static const bluecam = "assets/icons/bluecam1.svg";
  static const blueClock = "assets/icons/blueClock.svg";
  static const blueheart = "assets/icons/blueheart.svg";
  static const blueMapPoint = "assets/icons/blueomappoint.svg";
  static const bluesaved = "assets/icons/bluesaved.svg";
  static const bookconfirmpng = "assets/icons/bookConfirm1.png";
  static const Buildings = "assets/icons/Buildings.svg";
  static const callCut = "assets/icons/callCut.svg";
  static const cam = "assets/icons/cam.svg";
 static const camera = "assets/icons/camera.svg";
 static const camOff = "assets/icons/camOff.svg";
 static const camOn = "assets/icons/camOn.svg";
 static const camOnn = "assets/icons/camOnn.svg";
 static const camrotate = "assets/icons/camrotate.svg";
 static const cancel = "assets/icons/cancel.svg";
 static const cancelticketpng = "assets/icons/cancelticket.png";
 static const chatDelete = "assets/icons/chatDelete.png";
 static const checkbox = "assets/icons/Checkbox.svg";
 static const comingsoonpng = "assets/icons/comingsoon.png";
 // static const comingsoon = "assets/icons/comingsoon1.svg";
 static const congo="assets/icons/congo.svg";
 static const cross = "assets/icons/cross.svg";
 static const crownwithround = "assets/icons/crownwithround.svg";
 static const datePicker = "assets/icons/datePicker.svg";
 static const dating = "assets/icons/dating.svg";
 static const delete = "assets/icons/delete.svg";
 static const deletechaticon = "assets/icons/deletechaticon.svg";
 static const deviceManagement = "assets/icons/device_management.svg";
 static const discovery = "assets/icons/discovery.svg";
 static const dislike = "assets/icons/dislike.svg";
 static const editProfileBlack = "assets/icons/editProfileBlack.svg";
 static const education = "assets/icons/education.svg";
 static const Ellipse = "assets/icons/Ellipse.svg";
 static const mailIcon = "assets/icons/email.svg";
 static const emoji = "assets/icons/emoji.svg";
 static const eventbluesaved = "assets/icons/eventBlueSaved.svg";
 static const eventflower = "assets/icons/eventflower.svg";
 static const eventmappoint = "assets/icons/eventmappoint.svg";
 static const evntfreeicon = "assets/icons/evntfreeicon.svg";
 static const eyeOff = "assets/icons/EyeOff.svg";
 static const eyeOn = "assets/icons/EyeOn.svg";
 static const facebook = "assets/icons/facebook.png";
 static const FAQ = "assets/icons/FAQ.svg";
  static const filterIcon = "assets/icons/Filter.svg";
  static const FilterCircle = "assets/icons/FilterCircle.svg";
  static const reelFilterIcon = "assets/icons/filterIcon.svg";
  static const floatiAction = "assets/icons/floatiAction.svg";
  static const floatiActionp = "assets/icons/floatiAction.png";
  static const freeEventbookpng = "assets/icons/freeEventBook1.png";
  static const gallery = "assets/icons/gallery.svg";
  static const gallerygrey = "assets/icons/gallerygrey.svg";
  static const getVerified = "assets/icons/getVerified.png";
  static const giftext = "assets/icons/GIF.svg";
  static const google = "assets/icons/google.png";
  static const crownOff = "assets/icons/greycrown.svg";
  static const greydivider = "assets/icons/greydivider.svg";
  static const greyfemale = "assets/icons/greyfemale.svg";
  static const greyhieght = "assets/icons/greyhieght.svg";
  static const greyideal = "assets/icons/greyideal.svg";
  static const greyman = "assets/icons/greyman.svg";
  static const greyoutlineheart = "assets/icons/greyoutlineheart.svg";
  static const greysaved = "assets/icons/greysaved.svg";
  static const greyshefhat = "assets/icons/greyshefhat.svg";
  static const greysmoking = "assets/icons/greysmoking.svg";
  static const greySpark = "assets/icons/greySpark.svg";
  static const guide1 = "assets/icons/guide1.png";//
  static const guide3 = "assets/icons/guide2.png";
  static const guide2 = "assets/icons/guide3.png";
  static const heart = "assets/icons/heart.svg";
  static const heartblnkbg = "assets/icons/heartblnkbg.svg";
  static const historyIcon = "assets/icons/history.svg";
  static const iIcon = "assets/icons/iIcons.svg";
  static const inactive = "assets/icons/inactive.svg";
  static const infoicon = "assets/icons/infoicon.svg";
  static const leftup = "assets/icons/leftup.svg";
  static const like = "assets/icons/like.svg";
  static const locationIcon = "assets/icons/location.svg";
  static const locationAccess="assets/icons/locationAccess.svg";
  static const lock = "assets/icons/lock.svg";
  static const logoutpng="assets/icons/logout.png";
  static const unMatch="assets/icons/unmatch.png";
  static const logout = "assets/icons/Logout.svg";
  static const blueTickCheck = "assets/icons/looking_check.svg";
  static const magniferIcon = "assets/icons/Magnifer.svg";
  static const man = "assets/icons/man.svg";
  static const micOff = "assets/icons/micOff.svg";
  static const micOn = "assets/icons/micOn.svg";
  static const microphone = "assets/icons/microphone.svg";
  static const microphoneOn = "assets/icons/microphoneOn.svg";
  static const Mute = "assets/icons/mute.svg";
  static const noAds = "assets/icons/no_ads.svg";
  static const noMessage = "assets/icons/noMessage.png";
  static const notificationIcon = "assets/icons/notification.svg";
  static const notificationI = "assets/icons/notificationI.svg";
  static const notificationicon = "assets/icons/notificationicon.svg";
  static const orangecross = "assets/icons/orangecross.svg";
  static const outlinecalender = "assets/icons/outlinecalender.svg";
  static const payment_history = "assets/icons/payment_history.svg";
  static const pointingFingerpng = "assets/icons/pointingFinger.png";
  static const profileEdit = "assets/icons/profileEdit.svg";
  static const profileEdit1 = "assets/icons/profileEdit1.svg";
  static const uploadVideoIcon = "assets/icons/profile_video.svg";
  static const rightArrow = "assets/icons/right_arrow.svg";
  static const rightup = "assets/icons/rightup.svg";
  static const rightupLong = "assets/icons/rightupLong.svg";
  // static const saved = "assets/icons/saved.svg";
  static const savedsetting = "assets/icons/savedsetting.svg";
  static const notification = "assets/icons/settings_Notification.svg";
  static const setting = "assets/icons/setting.svg";
  static const shock = "assets/icons/shock.svg";
  static const sliderleft = "assets/icons/sliderleft.svg";
  // static const sliderright = "assets/icons/sliderright.svg";
  static const smiley = "assets/icons/smiley.svg";
  static const sparkWhiteCirlce = "assets/icons/sparkWhiteCirlce.svg";
  static const star = "assets/icons/star.svg";
  static const whiteeye = "assets/icons/whiteeye.svg";
  static const superlike = "assets/icons/superlike.svg";
  static const superlikewhite = "assets/icons/superlikewhite.svg";
  static const terms = "assets/icons/terms.svg";
  static const contactus = "assets/icons/contactus.svg";
  // static const ticketsheet = "assets/icons/ticketsheet.svg";
  static const timerCircle = "assets/icons/timerCircle.svg";
  static const transGenderBlack = "assets/icons/transgender_black.svg";
  static const transGenderWhite = "assets/icons/transgenderwhite.svg";
  // static const unMatchedIcon = "assets/icons/unMatchedIcon.png";//
  static const unMute = "assets/icons/unmute.svg";
  static const uploadPictureIcon = "assets/icons/uploadPicture.svg";
  static const demouser = "assets/icons/user.png";
  static const userIcon = "assets/icons/User.svg";
  static const verificationComplete = "assets/icons/verificationComplete.png";
  // static const verify = "assets/icons/verify.svg";
  static const verify = "assets/icons/verifywithborder.svg";
  static const verifygrey = "assets/icons/verifygrey.svg";
  static const verifyWhite = "assets/icons/verifyWhite.svg";
  static const verifywithborder = "assets/icons/verifywithborder.svg";
  static const verticaldivider = "assets/icons/verticaldivider.svg";
  static const videoplayicon = "assets/icons/videoplayicon.svg";
  static const watch = "assets/icons/watch.svg";
  static const whitearrowleft = "assets/icons/whitearrowleft.svg";
  static const whiteCancel = "assets/icons/whiteCancel.svg";
  static const crownOn = "assets/icons/whitecrown.svg";
  static const whiteFace = "assets/icons/whiteFace.svg";
  static const whitemappoint = "assets/icons/whitemappoint.svg";
  static const whiteSpark = "assets/icons/whiteSpark.svg";
  static const whitewatch = "assets/icons/whitewatch.svg";
  static const woman = "assets/icons/woman.svg";
  static const zoomIcon = "assets/icons/zoomIcon.svg";
  static const notificationLike = "assets/icons/notificationlike.svg";
  static const notificationDislike = "assets/icons/notificationdislike.svg";


//TODO===========> images
 // static const smiley1 = "assets/images/smiley1.png";
 // static const smiley2 = "assets/images/smiley2.png";
 // static const smiley3 = "assets/images/smiley3.png";
 // static const smiley4 = "assets/images/smiley4.png";
 // static const smiley5 = "assets/images/smiley5.png";
 static const smiley1svg = "assets/images/1.svg";
 static const smiley2svg = "assets/images/2.svg";
 static const smiley3svg = "assets/images/3.svg";
 static const smiley4svg = "assets/images/4.svg";
 static const smiley5svg = "assets/images/5.svg";
 static const accountLock = "assets/images/account_lock.svg";
 static const BG = "assets/images/BG.png";
 // static const eventProfile = "assets/images/eventProfile.png";
 static const example1 = "assets/images/example1.png";
 static const example2 = "assets/images/example2.png";
 static const example3 = "assets/images/example3.png";
 static const example4 = "assets/images/example4.png";
 static const example5 = "assets/images/example5.png";
 // static const likedYoupng = "assets/images/likedYou.png";
 static const likedYoupng1 = "assets/images/likedYou1.png";
 static const lockImg = "assets/images/Lock_img.svg";
 static const mailImg = "assets/images/mailImg.svg";
 static const mailImg2 = "assets/images/mailImg2.svg";
 static const matchespng = "assets/images/matches.png";
 static const matchespng1 = "assets/images/matches1.png";
 // static const meterbox = "assets/images/meterbox.svg";//
 static String splashp = "assets/images/name.png";
 static const noevent = "assets/images/noevent.png";
 static const nonotification = "assets/images/nonotification.png";
 // static const progressbullet = "assets/images/progressbullet.svg";//
 static const sparkleft = "assets/images/spark.png";
 static const sparkempty = "assets/images/sparkempty.png";
 static const threeDots = "assets/images/three_dots.svg";
 static const threeDotsLeft = "assets/images/threeDotsLeft.svg";
 static const ticketbackground = "assets/images/ticket_background.png";//
 // static const videoThumb = "assets/images/videoThumb.png";//

 //TODO===========> sample
 static const matchingSample = "assets/sample/matchingSample.png";
 // static const matchingSampleSvg = "assets/sample/matchingSample.svg";
 // static const photo = "assets/sample/photo.png";
 static const redHeart = "assets/sample/redHeart1.svg";
 // static const sampleperson = "assets/sample/sampleperson.png";
 static const twoHeart = "assets/sample/twoHeart.svg";
}
