import 'dart:io';

import 'package:in_app_purchase/in_app_purchase.dart';

class LocaleHandler {
  static String channelId="";
  static String rtctoken="";
  static String accessToken = "";
  static String socialLogin = "no";
  static String fcmToken = "";
  static String bearer = "Bearer ${accessToken}";
  static String refreshToken = "";
  static String resetPasswordtoken = "";
  static String nextAction = "";
  static String nextDetailAction = "fill_ideal_vacation";
  static String userId = "";
  static String subscriptionPurchase = "";
  static String role = "";
  static String emailVerified = "";
  static String name = "";
  static String dateTimee = "";
  static String avatar = "";
  static String height = "";
  static String education = "";
  static String heighttype = "cm";
  static String showheights = "true";
  static String gender = "";
  static String filtergender = "";
  static String showgenders = "true";
  static String lookingfor = "";
  static String sexualOreintation = "";
  static String location = "";
  static String jobtitle = "";
  static String companyName = "";
  static String ideal = "";
  static String distance = "5000";
  static String cookingSkill = "";
  static String smokingopinion = "";
  static String latitude = "36.7783";
  static String longitude = "119.4179";
  static String freeEventImage = '';
  static String ErrorMessage = '';

  static int bottomSheetIndex = 0;
  static int dateno = 0;
  static int totalDate = 1;
  static int miliseconds = 0;
  static int eventId = 0;
  static int distancee = 500;
  static int curentIndexNum = 0;
  static int pageIndex = 0;
  static int distancevalue=500;
  static int startage=18;
  static int endage=100;
  static int selectedIndexGender=-1;

  static bool isThereAnyEvent = false;
  static bool isThereCancelEvent = false;
  static bool unMatchedEvent = false;
  static bool isBanner = false;
  static bool isBanner2 = false;
  static bool bannerInReel = false;
  static bool isProtected = false;
  static bool subScribtioonOffer = false;
  static bool passwordField = false;
  static bool EditProfile = false;
  static bool basicInfo = true;
  static bool passMatched = false;
  static bool cpassMatched = false;
  static bool reportedSuccesfuly = false;
  static bool matchedd = false;
  static bool feedTutorials = true;
  static bool isLikedTabUpdate = false;
  static bool isChecked=false;
  static bool bioAuth=false;
  static bool speeddatePermission=false;
  static bool liked=false;
  static bool insideevent=false;
  static bool lateEntry=false;
  static String bioAuth2="false";
  static bool noInternet=false;
  static bool micOn=false;
  static bool onCamPrefrencescreen=false;
  static bool camOn=false;
  static bool showgender = true;
  static bool showlookingfor = true;
  static bool isVerified = false;
  static String showsexualOreintations = "true";
  static bool cordinatesFetch = false;

  static List entencity = [];
  static List entencityname = [];
  static List fixtureParticipantId = [];
  static List items = [];
  static File? introImage;
  static File? introVideo;
  static Map<String, dynamic> dataa = {};
  static Map<String, dynamic> eventdataa = {};
  static Map<String, dynamic> eventParticipantData = {};
  static List<String> switchitem = [];
}


