// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "",
    appId: "",
    messagingSenderId: "",
    projectId: "",
    storageBucket: "",
    authDomain: "",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD4g9d7N0HaM4a5sXIVjqdX6IU1dFAQog',
    appId: '1:422898489031:android:b7d621a5a4a9bdcb0bd0e2',
    messagingSenderId: '422898489031',
    projectId: 'virtual-speed-date-325915',
    storageBucket: "virtual-speed-date-325915.appspot.com",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMjiyaz61KrWi50WgJYOzmAr4ojqQ-Y7w',
    appId: '1:422898489031:ios:f16edecd3a83915d0bd0e2',
    messagingSenderId: '422898489031',
    projectId: 'virtual-speed-date-325915',
    storageBucket: 'virtual-speed-date-325915.appspot.com',
    iosClientId: '422898489031-h5ij8sg3n5iunf63qqo62p9uc2baccj8.apps.googleusercontent.com',
    iosBundleId: 'com.slushdating.slush',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '',
    messagingSenderId: '',
    projectId: '',
    storageBucket: '',
    iosClientId: '',
    iosBundleId: '',
  );
}